### ISSUE TITLE
Create docker image to run w3af inside

### ISSUE THREAD

**Issue by andresriancho** [andresriancho/collector#11]
Create docker image to run w3af inside which will speedup the setup phase. Remember that we have to re-compile python now to have support for some of our tools.

## TODO
 - [ ] Create a `Dockerfile` in collector/examples/w3af based on [the w3af docker image](https://registry.hub.docker.com/u/andresriancho/w3af/) but installing all the other things I need for profiling
 - [ ] Also update the `ami` to point to one that already has docker installed:
```yaml
main:
  ami: ami-48eb2f20
```
 - [ ] Create a script to run w3af inside docker and save the profiling output to a place where I can easily download afterwards
